// GENERATED 2026-06-11 by an 8-agent workflow (4 regional generators +
// 3 adversarial verifiers) with the skeptic-agreed corrections applied:
// 865 Navajo Nation -> Denver (observes DST), 498/499 UP -> Detroit
// (population majority), 341 Naples FL added, Kazakhstan single-zone
// (2024 law). Coarse by design: a zip3 maps to its MAJORITY zone; the
// device clock stays the primary source. Regenerate rather than hand-edit.

/** US 3-digit ZIP prefix -> IANA timezone (majority of the prefix). */
export const US_ZIP3_TO_TZ: Record<string, string> = {
  "005": "America/New_York",
  "006": "America/Puerto_Rico",
  "007": "America/Puerto_Rico",
  "008": "America/Puerto_Rico",
  "009": "America/Puerto_Rico",
  "010": "America/New_York",
  "011": "America/New_York",
  "012": "America/New_York",
  "013": "America/New_York",
  "014": "America/New_York",
  "015": "America/New_York",
  "016": "America/New_York",
  "017": "America/New_York",
  "018": "America/New_York",
  "019": "America/New_York",
  "020": "America/New_York",
  "021": "America/New_York",
  "022": "America/New_York",
  "023": "America/New_York",
  "024": "America/New_York",
  "025": "America/New_York",
  "026": "America/New_York",
  "027": "America/New_York",
  "028": "America/New_York",
  "029": "America/New_York",
  "030": "America/New_York",
  "031": "America/New_York",
  "032": "America/New_York",
  "033": "America/New_York",
  "034": "America/New_York",
  "035": "America/New_York",
  "036": "America/New_York",
  "037": "America/New_York",
  "038": "America/New_York",
  "039": "America/New_York",
  "040": "America/New_York",
  "041": "America/New_York",
  "042": "America/New_York",
  "043": "America/New_York",
  "044": "America/New_York",
  "045": "America/New_York",
  "046": "America/New_York",
  "047": "America/New_York",
  "048": "America/New_York",
  "049": "America/New_York",
  "050": "America/New_York",
  "051": "America/New_York",
  "052": "America/New_York",
  "053": "America/New_York",
  "054": "America/New_York",
  "055": "America/New_York",
  "056": "America/New_York",
  "057": "America/New_York",
  "058": "America/New_York",
  "059": "America/New_York",
  "060": "America/New_York",
  "061": "America/New_York",
  "062": "America/New_York",
  "063": "America/New_York",
  "064": "America/New_York",
  "065": "America/New_York",
  "066": "America/New_York",
  "067": "America/New_York",
  "068": "America/New_York",
  "069": "America/New_York",
  "070": "America/New_York",
  "071": "America/New_York",
  "072": "America/New_York",
  "073": "America/New_York",
  "074": "America/New_York",
  "075": "America/New_York",
  "076": "America/New_York",
  "077": "America/New_York",
  "078": "America/New_York",
  "079": "America/New_York",
  "080": "America/New_York",
  "081": "America/New_York",
  "082": "America/New_York",
  "083": "America/New_York",
  "084": "America/New_York",
  "085": "America/New_York",
  "086": "America/New_York",
  "087": "America/New_York",
  "088": "America/New_York",
  "089": "America/New_York",
  "100": "America/New_York",
  "101": "America/New_York",
  "102": "America/New_York",
  "103": "America/New_York",
  "104": "America/New_York",
  "105": "America/New_York",
  "106": "America/New_York",
  "107": "America/New_York",
  "108": "America/New_York",
  "109": "America/New_York",
  "110": "America/New_York",
  "111": "America/New_York",
  "112": "America/New_York",
  "113": "America/New_York",
  "114": "America/New_York",
  "115": "America/New_York",
  "116": "America/New_York",
  "117": "America/New_York",
  "118": "America/New_York",
  "119": "America/New_York",
  "120": "America/New_York",
  "121": "America/New_York",
  "122": "America/New_York",
  "123": "America/New_York",
  "124": "America/New_York",
  "125": "America/New_York",
  "126": "America/New_York",
  "127": "America/New_York",
  "128": "America/New_York",
  "129": "America/New_York",
  "130": "America/New_York",
  "131": "America/New_York",
  "132": "America/New_York",
  "133": "America/New_York",
  "134": "America/New_York",
  "135": "America/New_York",
  "136": "America/New_York",
  "137": "America/New_York",
  "138": "America/New_York",
  "139": "America/New_York",
  "140": "America/New_York",
  "141": "America/New_York",
  "142": "America/New_York",
  "143": "America/New_York",
  "144": "America/New_York",
  "145": "America/New_York",
  "146": "America/New_York",
  "147": "America/New_York",
  "148": "America/New_York",
  "149": "America/New_York",
  "150": "America/New_York",
  "151": "America/New_York",
  "152": "America/New_York",
  "153": "America/New_York",
  "154": "America/New_York",
  "155": "America/New_York",
  "156": "America/New_York",
  "157": "America/New_York",
  "158": "America/New_York",
  "159": "America/New_York",
  "160": "America/New_York",
  "161": "America/New_York",
  "162": "America/New_York",
  "163": "America/New_York",
  "164": "America/New_York",
  "165": "America/New_York",
  "166": "America/New_York",
  "167": "America/New_York",
  "168": "America/New_York",
  "169": "America/New_York",
  "170": "America/New_York",
  "171": "America/New_York",
  "172": "America/New_York",
  "173": "America/New_York",
  "174": "America/New_York",
  "175": "America/New_York",
  "176": "America/New_York",
  "177": "America/New_York",
  "178": "America/New_York",
  "179": "America/New_York",
  "180": "America/New_York",
  "181": "America/New_York",
  "182": "America/New_York",
  "183": "America/New_York",
  "184": "America/New_York",
  "185": "America/New_York",
  "186": "America/New_York",
  "187": "America/New_York",
  "188": "America/New_York",
  "189": "America/New_York",
  "190": "America/New_York",
  "191": "America/New_York",
  "192": "America/New_York",
  "193": "America/New_York",
  "194": "America/New_York",
  "195": "America/New_York",
  "196": "America/New_York",
  "197": "America/New_York",
  "198": "America/New_York",
  "199": "America/New_York",
  "200": "America/New_York",
  "201": "America/New_York",
  "202": "America/New_York",
  "203": "America/New_York",
  "204": "America/New_York",
  "205": "America/New_York",
  "206": "America/New_York",
  "207": "America/New_York",
  "208": "America/New_York",
  "209": "America/New_York",
  "210": "America/New_York",
  "211": "America/New_York",
  "212": "America/New_York",
  "214": "America/New_York",
  "215": "America/New_York",
  "216": "America/New_York",
  "217": "America/New_York",
  "218": "America/New_York",
  "219": "America/New_York",
  "220": "America/New_York",
  "221": "America/New_York",
  "222": "America/New_York",
  "223": "America/New_York",
  "224": "America/New_York",
  "225": "America/New_York",
  "226": "America/New_York",
  "227": "America/New_York",
  "228": "America/New_York",
  "229": "America/New_York",
  "230": "America/New_York",
  "231": "America/New_York",
  "232": "America/New_York",
  "233": "America/New_York",
  "234": "America/New_York",
  "235": "America/New_York",
  "236": "America/New_York",
  "237": "America/New_York",
  "238": "America/New_York",
  "239": "America/New_York",
  "240": "America/New_York",
  "241": "America/New_York",
  "242": "America/New_York",
  "243": "America/New_York",
  "244": "America/New_York",
  "245": "America/New_York",
  "246": "America/New_York",
  "247": "America/New_York",
  "248": "America/New_York",
  "249": "America/New_York",
  "250": "America/New_York",
  "251": "America/New_York",
  "252": "America/New_York",
  "253": "America/New_York",
  "254": "America/New_York",
  "255": "America/New_York",
  "256": "America/New_York",
  "257": "America/New_York",
  "258": "America/New_York",
  "259": "America/New_York",
  "260": "America/New_York",
  "261": "America/New_York",
  "262": "America/New_York",
  "263": "America/New_York",
  "264": "America/New_York",
  "265": "America/New_York",
  "266": "America/New_York",
  "267": "America/New_York",
  "268": "America/New_York",
  "270": "America/New_York",
  "271": "America/New_York",
  "272": "America/New_York",
  "273": "America/New_York",
  "274": "America/New_York",
  "275": "America/New_York",
  "276": "America/New_York",
  "277": "America/New_York",
  "278": "America/New_York",
  "279": "America/New_York",
  "280": "America/New_York",
  "281": "America/New_York",
  "282": "America/New_York",
  "283": "America/New_York",
  "284": "America/New_York",
  "285": "America/New_York",
  "286": "America/New_York",
  "287": "America/New_York",
  "288": "America/New_York",
  "289": "America/New_York",
  "290": "America/New_York",
  "291": "America/New_York",
  "292": "America/New_York",
  "293": "America/New_York",
  "294": "America/New_York",
  "295": "America/New_York",
  "296": "America/New_York",
  "297": "America/New_York",
  "298": "America/New_York",
  "299": "America/New_York",
  "300": "America/New_York",
  "301": "America/New_York",
  "302": "America/New_York",
  "303": "America/New_York",
  "304": "America/New_York",
  "305": "America/New_York",
  "306": "America/New_York",
  "307": "America/New_York",
  "308": "America/New_York",
  "309": "America/New_York",
  "310": "America/New_York",
  "311": "America/New_York",
  "312": "America/New_York",
  "313": "America/New_York",
  "314": "America/New_York",
  "315": "America/New_York",
  "316": "America/New_York",
  "317": "America/New_York",
  "318": "America/New_York",
  "319": "America/New_York",
  "320": "America/New_York",
  "321": "America/New_York",
  "322": "America/New_York",
  "323": "America/New_York",
  "324": "America/Chicago",
  "325": "America/Chicago",
  "326": "America/New_York",
  "327": "America/New_York",
  "328": "America/New_York",
  "329": "America/New_York",
  "330": "America/New_York",
  "331": "America/New_York",
  "332": "America/New_York",
  "333": "America/New_York",
  "334": "America/New_York",
  "335": "America/New_York",
  "336": "America/New_York",
  "337": "America/New_York",
  "338": "America/New_York",
  "339": "America/New_York",
  "341": "America/New_York",
  "342": "America/New_York",
  "344": "America/New_York",
  "346": "America/New_York",
  "347": "America/New_York",
  "349": "America/New_York",
  "350": "America/Chicago",
  "351": "America/Chicago",
  "352": "America/Chicago",
  "354": "America/Chicago",
  "355": "America/Chicago",
  "356": "America/Chicago",
  "357": "America/Chicago",
  "358": "America/Chicago",
  "359": "America/Chicago",
  "360": "America/Chicago",
  "361": "America/Chicago",
  "362": "America/Chicago",
  "363": "America/Chicago",
  "364": "America/Chicago",
  "365": "America/Chicago",
  "366": "America/Chicago",
  "367": "America/Chicago",
  "368": "America/Chicago",
  "369": "America/Chicago",
  "370": "America/Chicago",
  "371": "America/Chicago",
  "372": "America/Chicago",
  "373": "America/New_York",
  "374": "America/New_York",
  "375": "America/Chicago",
  "376": "America/New_York",
  "377": "America/New_York",
  "378": "America/New_York",
  "379": "America/New_York",
  "380": "America/Chicago",
  "381": "America/Chicago",
  "382": "America/Chicago",
  "383": "America/Chicago",
  "384": "America/Chicago",
  "385": "America/Chicago",
  "386": "America/Chicago",
  "387": "America/Chicago",
  "388": "America/Chicago",
  "389": "America/Chicago",
  "390": "America/Chicago",
  "391": "America/Chicago",
  "392": "America/Chicago",
  "393": "America/Chicago",
  "394": "America/Chicago",
  "395": "America/Chicago",
  "396": "America/Chicago",
  "397": "America/Chicago",
  "398": "America/New_York",
  "399": "America/New_York",
  "400": "America/Kentucky/Louisville",
  "401": "America/Kentucky/Louisville",
  "402": "America/Kentucky/Louisville",
  "403": "America/New_York",
  "404": "America/New_York",
  "405": "America/New_York",
  "406": "America/New_York",
  "407": "America/New_York",
  "408": "America/New_York",
  "409": "America/New_York",
  "410": "America/New_York",
  "411": "America/New_York",
  "412": "America/New_York",
  "413": "America/New_York",
  "414": "America/New_York",
  "415": "America/New_York",
  "416": "America/New_York",
  "417": "America/New_York",
  "418": "America/New_York",
  "420": "America/Chicago",
  "421": "America/Chicago",
  "422": "America/Chicago",
  "423": "America/Chicago",
  "424": "America/Chicago",
  "425": "America/New_York",
  "426": "America/New_York",
  "427": "America/New_York",
  "430": "America/New_York",
  "431": "America/New_York",
  "432": "America/New_York",
  "433": "America/New_York",
  "434": "America/New_York",
  "435": "America/New_York",
  "436": "America/New_York",
  "437": "America/New_York",
  "438": "America/New_York",
  "439": "America/New_York",
  "440": "America/New_York",
  "441": "America/New_York",
  "442": "America/New_York",
  "443": "America/New_York",
  "444": "America/New_York",
  "445": "America/New_York",
  "446": "America/New_York",
  "447": "America/New_York",
  "448": "America/New_York",
  "449": "America/New_York",
  "450": "America/New_York",
  "451": "America/New_York",
  "452": "America/New_York",
  "453": "America/New_York",
  "454": "America/New_York",
  "455": "America/New_York",
  "456": "America/New_York",
  "457": "America/New_York",
  "458": "America/New_York",
  "459": "America/New_York",
  "460": "America/Indiana/Indianapolis",
  "461": "America/Indiana/Indianapolis",
  "462": "America/Indiana/Indianapolis",
  "463": "America/Chicago",
  "464": "America/Chicago",
  "465": "America/Indiana/Indianapolis",
  "466": "America/Indiana/Indianapolis",
  "467": "America/Indiana/Indianapolis",
  "468": "America/Indiana/Indianapolis",
  "469": "America/Indiana/Indianapolis",
  "470": "America/Indiana/Indianapolis",
  "471": "America/Indiana/Indianapolis",
  "472": "America/Indiana/Indianapolis",
  "473": "America/Indiana/Indianapolis",
  "474": "America/Indiana/Indianapolis",
  "475": "America/Indiana/Indianapolis",
  "476": "America/Chicago",
  "477": "America/Chicago",
  "478": "America/Indiana/Indianapolis",
  "479": "America/Indiana/Indianapolis",
  "480": "America/Detroit",
  "481": "America/Detroit",
  "482": "America/Detroit",
  "483": "America/Detroit",
  "484": "America/Detroit",
  "485": "America/Detroit",
  "486": "America/Detroit",
  "487": "America/Detroit",
  "488": "America/Detroit",
  "489": "America/Detroit",
  "490": "America/Detroit",
  "491": "America/Detroit",
  "492": "America/Detroit",
  "493": "America/Detroit",
  "494": "America/Detroit",
  "495": "America/Detroit",
  "496": "America/Detroit",
  "497": "America/Detroit",
  "498": "America/Detroit",
  "499": "America/Detroit",
  "500": "America/Chicago",
  "501": "America/Chicago",
  "502": "America/Chicago",
  "503": "America/Chicago",
  "504": "America/Chicago",
  "505": "America/Chicago",
  "506": "America/Chicago",
  "507": "America/Chicago",
  "508": "America/Chicago",
  "509": "America/Chicago",
  "510": "America/Chicago",
  "511": "America/Chicago",
  "512": "America/Chicago",
  "513": "America/Chicago",
  "514": "America/Chicago",
  "515": "America/Chicago",
  "516": "America/Chicago",
  "520": "America/Chicago",
  "521": "America/Chicago",
  "522": "America/Chicago",
  "523": "America/Chicago",
  "524": "America/Chicago",
  "525": "America/Chicago",
  "526": "America/Chicago",
  "527": "America/Chicago",
  "528": "America/Chicago",
  "530": "America/Chicago",
  "531": "America/Chicago",
  "532": "America/Chicago",
  "534": "America/Chicago",
  "535": "America/Chicago",
  "537": "America/Chicago",
  "538": "America/Chicago",
  "539": "America/Chicago",
  "540": "America/Chicago",
  "541": "America/Chicago",
  "542": "America/Chicago",
  "543": "America/Chicago",
  "544": "America/Chicago",
  "545": "America/Chicago",
  "546": "America/Chicago",
  "547": "America/Chicago",
  "548": "America/Chicago",
  "549": "America/Chicago",
  "550": "America/Chicago",
  "551": "America/Chicago",
  "553": "America/Chicago",
  "554": "America/Chicago",
  "555": "America/Chicago",
  "556": "America/Chicago",
  "557": "America/Chicago",
  "558": "America/Chicago",
  "559": "America/Chicago",
  "560": "America/Chicago",
  "561": "America/Chicago",
  "562": "America/Chicago",
  "563": "America/Chicago",
  "564": "America/Chicago",
  "565": "America/Chicago",
  "566": "America/Chicago",
  "567": "America/Chicago",
  "569": "America/New_York",
  "570": "America/Chicago",
  "571": "America/Chicago",
  "572": "America/Chicago",
  "573": "America/Chicago",
  "574": "America/Chicago",
  "575": "America/Chicago",
  "576": "America/Chicago",
  "577": "America/Denver",
  "580": "America/Chicago",
  "581": "America/Chicago",
  "582": "America/Chicago",
  "583": "America/Chicago",
  "584": "America/Chicago",
  "585": "America/Chicago",
  "586": "America/Denver",
  "587": "America/Chicago",
  "588": "America/Chicago",
  "590": "America/Denver",
  "591": "America/Denver",
  "592": "America/Denver",
  "593": "America/Denver",
  "594": "America/Denver",
  "595": "America/Denver",
  "596": "America/Denver",
  "597": "America/Denver",
  "598": "America/Denver",
  "599": "America/Denver",
  "600": "America/Chicago",
  "601": "America/Chicago",
  "602": "America/Chicago",
  "603": "America/Chicago",
  "604": "America/Chicago",
  "605": "America/Chicago",
  "606": "America/Chicago",
  "607": "America/Chicago",
  "608": "America/Chicago",
  "609": "America/Chicago",
  "610": "America/Chicago",
  "611": "America/Chicago",
  "612": "America/Chicago",
  "613": "America/Chicago",
  "614": "America/Chicago",
  "615": "America/Chicago",
  "616": "America/Chicago",
  "617": "America/Chicago",
  "618": "America/Chicago",
  "619": "America/Chicago",
  "620": "America/Chicago",
  "622": "America/Chicago",
  "623": "America/Chicago",
  "624": "America/Chicago",
  "625": "America/Chicago",
  "626": "America/Chicago",
  "627": "America/Chicago",
  "628": "America/Chicago",
  "629": "America/Chicago",
  "630": "America/Chicago",
  "631": "America/Chicago",
  "633": "America/Chicago",
  "634": "America/Chicago",
  "635": "America/Chicago",
  "636": "America/Chicago",
  "637": "America/Chicago",
  "638": "America/Chicago",
  "639": "America/Chicago",
  "640": "America/Chicago",
  "641": "America/Chicago",
  "644": "America/Chicago",
  "645": "America/Chicago",
  "646": "America/Chicago",
  "647": "America/Chicago",
  "648": "America/Chicago",
  "649": "America/Chicago",
  "650": "America/Chicago",
  "651": "America/Chicago",
  "652": "America/Chicago",
  "653": "America/Chicago",
  "654": "America/Chicago",
  "655": "America/Chicago",
  "656": "America/Chicago",
  "657": "America/Chicago",
  "658": "America/Chicago",
  "660": "America/Chicago",
  "661": "America/Chicago",
  "662": "America/Chicago",
  "664": "America/Chicago",
  "665": "America/Chicago",
  "666": "America/Chicago",
  "667": "America/Chicago",
  "668": "America/Chicago",
  "669": "America/Chicago",
  "670": "America/Chicago",
  "671": "America/Chicago",
  "672": "America/Chicago",
  "673": "America/Chicago",
  "674": "America/Chicago",
  "675": "America/Chicago",
  "676": "America/Chicago",
  "677": "America/Chicago",
  "678": "America/Chicago",
  "679": "America/Chicago",
  "680": "America/Chicago",
  "681": "America/Chicago",
  "683": "America/Chicago",
  "684": "America/Chicago",
  "685": "America/Chicago",
  "686": "America/Chicago",
  "687": "America/Chicago",
  "688": "America/Chicago",
  "689": "America/Chicago",
  "690": "America/Chicago",
  "691": "America/Chicago",
  "692": "America/Chicago",
  "693": "America/Denver",
  "700": "America/Chicago",
  "701": "America/Chicago",
  "703": "America/Chicago",
  "704": "America/Chicago",
  "705": "America/Chicago",
  "706": "America/Chicago",
  "707": "America/Chicago",
  "708": "America/Chicago",
  "710": "America/Chicago",
  "711": "America/Chicago",
  "712": "America/Chicago",
  "713": "America/Chicago",
  "714": "America/Chicago",
  "716": "America/Chicago",
  "717": "America/Chicago",
  "718": "America/Chicago",
  "719": "America/Chicago",
  "720": "America/Chicago",
  "721": "America/Chicago",
  "722": "America/Chicago",
  "723": "America/Chicago",
  "724": "America/Chicago",
  "725": "America/Chicago",
  "726": "America/Chicago",
  "727": "America/Chicago",
  "728": "America/Chicago",
  "729": "America/Chicago",
  "730": "America/Chicago",
  "731": "America/Chicago",
  "733": "America/Chicago",
  "734": "America/Chicago",
  "735": "America/Chicago",
  "736": "America/Chicago",
  "737": "America/Chicago",
  "738": "America/Chicago",
  "739": "America/Chicago",
  "740": "America/Chicago",
  "741": "America/Chicago",
  "743": "America/Chicago",
  "744": "America/Chicago",
  "745": "America/Chicago",
  "746": "America/Chicago",
  "747": "America/Chicago",
  "748": "America/Chicago",
  "749": "America/Chicago",
  "750": "America/Chicago",
  "751": "America/Chicago",
  "752": "America/Chicago",
  "753": "America/Chicago",
  "754": "America/Chicago",
  "755": "America/Chicago",
  "756": "America/Chicago",
  "757": "America/Chicago",
  "758": "America/Chicago",
  "759": "America/Chicago",
  "760": "America/Chicago",
  "761": "America/Chicago",
  "762": "America/Chicago",
  "763": "America/Chicago",
  "764": "America/Chicago",
  "765": "America/Chicago",
  "766": "America/Chicago",
  "767": "America/Chicago",
  "768": "America/Chicago",
  "769": "America/Chicago",
  "770": "America/Chicago",
  "771": "America/Chicago",
  "772": "America/Chicago",
  "773": "America/Chicago",
  "774": "America/Chicago",
  "775": "America/Chicago",
  "776": "America/Chicago",
  "777": "America/Chicago",
  "778": "America/Chicago",
  "779": "America/Chicago",
  "780": "America/Chicago",
  "781": "America/Chicago",
  "782": "America/Chicago",
  "783": "America/Chicago",
  "784": "America/Chicago",
  "785": "America/Chicago",
  "786": "America/Chicago",
  "787": "America/Chicago",
  "788": "America/Chicago",
  "789": "America/Chicago",
  "790": "America/Chicago",
  "791": "America/Chicago",
  "792": "America/Chicago",
  "793": "America/Chicago",
  "794": "America/Chicago",
  "795": "America/Chicago",
  "796": "America/Chicago",
  "797": "America/Chicago",
  "798": "America/Denver",
  "799": "America/Denver",
  "800": "America/Denver",
  "801": "America/Denver",
  "802": "America/Denver",
  "803": "America/Denver",
  "804": "America/Denver",
  "805": "America/Denver",
  "806": "America/Denver",
  "807": "America/Denver",
  "808": "America/Denver",
  "809": "America/Denver",
  "810": "America/Denver",
  "811": "America/Denver",
  "812": "America/Denver",
  "813": "America/Denver",
  "814": "America/Denver",
  "815": "America/Denver",
  "816": "America/Denver",
  "820": "America/Denver",
  "821": "America/Denver",
  "822": "America/Denver",
  "823": "America/Denver",
  "824": "America/Denver",
  "825": "America/Denver",
  "826": "America/Denver",
  "827": "America/Denver",
  "828": "America/Denver",
  "829": "America/Denver",
  "830": "America/Denver",
  "831": "America/Denver",
  "832": "America/Boise",
  "833": "America/Boise",
  "834": "America/Boise",
  "835": "America/Los_Angeles",
  "836": "America/Boise",
  "837": "America/Boise",
  "838": "America/Los_Angeles",
  "840": "America/Denver",
  "841": "America/Denver",
  "842": "America/Denver",
  "843": "America/Denver",
  "844": "America/Denver",
  "845": "America/Denver",
  "846": "America/Denver",
  "847": "America/Denver",
  "850": "America/Phoenix",
  "851": "America/Phoenix",
  "852": "America/Phoenix",
  "853": "America/Phoenix",
  "855": "America/Phoenix",
  "856": "America/Phoenix",
  "857": "America/Phoenix",
  "859": "America/Phoenix",
  "860": "America/Phoenix",
  "863": "America/Phoenix",
  "864": "America/Phoenix",
  "865": "America/Denver",
  "870": "America/Denver",
  "871": "America/Denver",
  "873": "America/Denver",
  "874": "America/Denver",
  "875": "America/Denver",
  "877": "America/Denver",
  "878": "America/Denver",
  "879": "America/Denver",
  "880": "America/Denver",
  "881": "America/Denver",
  "882": "America/Denver",
  "883": "America/Denver",
  "884": "America/Denver",
  "885": "America/Denver",
  "889": "America/Los_Angeles",
  "890": "America/Los_Angeles",
  "891": "America/Los_Angeles",
  "893": "America/Los_Angeles",
  "894": "America/Los_Angeles",
  "895": "America/Los_Angeles",
  "897": "America/Los_Angeles",
  "898": "America/Los_Angeles",
  "900": "America/Los_Angeles",
  "901": "America/Los_Angeles",
  "902": "America/Los_Angeles",
  "903": "America/Los_Angeles",
  "904": "America/Los_Angeles",
  "905": "America/Los_Angeles",
  "906": "America/Los_Angeles",
  "907": "America/Los_Angeles",
  "908": "America/Los_Angeles",
  "910": "America/Los_Angeles",
  "911": "America/Los_Angeles",
  "912": "America/Los_Angeles",
  "913": "America/Los_Angeles",
  "914": "America/Los_Angeles",
  "915": "America/Los_Angeles",
  "916": "America/Los_Angeles",
  "917": "America/Los_Angeles",
  "918": "America/Los_Angeles",
  "919": "America/Los_Angeles",
  "920": "America/Los_Angeles",
  "921": "America/Los_Angeles",
  "922": "America/Los_Angeles",
  "923": "America/Los_Angeles",
  "924": "America/Los_Angeles",
  "925": "America/Los_Angeles",
  "926": "America/Los_Angeles",
  "927": "America/Los_Angeles",
  "928": "America/Los_Angeles",
  "930": "America/Los_Angeles",
  "931": "America/Los_Angeles",
  "932": "America/Los_Angeles",
  "933": "America/Los_Angeles",
  "934": "America/Los_Angeles",
  "935": "America/Los_Angeles",
  "936": "America/Los_Angeles",
  "937": "America/Los_Angeles",
  "938": "America/Los_Angeles",
  "939": "America/Los_Angeles",
  "940": "America/Los_Angeles",
  "941": "America/Los_Angeles",
  "942": "America/Los_Angeles",
  "943": "America/Los_Angeles",
  "944": "America/Los_Angeles",
  "945": "America/Los_Angeles",
  "946": "America/Los_Angeles",
  "947": "America/Los_Angeles",
  "948": "America/Los_Angeles",
  "949": "America/Los_Angeles",
  "950": "America/Los_Angeles",
  "951": "America/Los_Angeles",
  "952": "America/Los_Angeles",
  "953": "America/Los_Angeles",
  "954": "America/Los_Angeles",
  "955": "America/Los_Angeles",
  "956": "America/Los_Angeles",
  "957": "America/Los_Angeles",
  "958": "America/Los_Angeles",
  "959": "America/Los_Angeles",
  "960": "America/Los_Angeles",
  "961": "America/Los_Angeles",
  "967": "Pacific/Honolulu",
  "968": "Pacific/Honolulu",
  "969": "Pacific/Guam",
  "970": "America/Los_Angeles",
  "971": "America/Los_Angeles",
  "972": "America/Los_Angeles",
  "973": "America/Los_Angeles",
  "974": "America/Los_Angeles",
  "975": "America/Los_Angeles",
  "976": "America/Los_Angeles",
  "977": "America/Los_Angeles",
  "978": "America/Los_Angeles",
  "979": "America/Boise",
  "980": "America/Los_Angeles",
  "981": "America/Los_Angeles",
  "982": "America/Los_Angeles",
  "983": "America/Los_Angeles",
  "984": "America/Los_Angeles",
  "985": "America/Los_Angeles",
  "986": "America/Los_Angeles",
  "988": "America/Los_Angeles",
  "989": "America/Los_Angeles",
  "990": "America/Los_Angeles",
  "991": "America/Los_Angeles",
  "992": "America/Los_Angeles",
  "993": "America/Los_Angeles",
  "994": "America/Los_Angeles",
  "995": "America/Anchorage",
  "996": "America/Anchorage",
  "997": "America/Anchorage",
  "998": "America/Anchorage",
  "999": "America/Anchorage",
};

/** Countries with effectively one civil timezone, by spoken name. */
export const COUNTRY_SINGLE_TZ: ReadonlyArray<{
  name: string;
  aliases: string[];
  tz: string;
}> = [
  { name: "Afghanistan", aliases: ["afghanistan", "afganistan", "afganist\u00e1n"], tz: "Asia/Kabul" },
  { name: "Albania", aliases: ["albania", "albanie", "albanien", "shqiperia"], tz: "Europe/Tirane" },
  { name: "Algeria", aliases: ["algeria", "argelia", "algerie", "alg\u00e9rie", "algerien"], tz: "Africa/Algiers" },
  { name: "Andorra", aliases: ["andorra"], tz: "Europe/Andorra" },
  { name: "Angola", aliases: ["angola"], tz: "Africa/Luanda" },
  { name: "Antigua and Barbuda", aliases: ["antigua", "antigua and barbuda"], tz: "America/Antigua" },
  { name: "Argentina", aliases: ["argentina", "argentine", "argentinien"], tz: "America/Argentina/Buenos_Aires" },
  { name: "Armenia", aliases: ["armenia", "armenie", "arm\u00e9nie", "armenien"], tz: "Asia/Yerevan" },
  { name: "Aruba", aliases: ["aruba"], tz: "America/Aruba" },
  { name: "Austria", aliases: ["austria", "osterreich", "\u00f6sterreich", "autriche"], tz: "Europe/Vienna" },
  { name: "Azerbaijan", aliases: ["azerbaijan", "azerbaiyan", "azerbaiy\u00e1n", "aserbaidschan", "azerbaidjan"], tz: "Asia/Baku" },
  { name: "Azores", aliases: ["azores", "the azores"], tz: "Atlantic/Azores" },
  { name: "Bahamas", aliases: ["bahamas", "the bahamas"], tz: "America/Nassau" },
  { name: "Bahrain", aliases: ["bahrain", "bahrein"], tz: "Asia/Bahrain" },
  { name: "Bangladesh", aliases: ["bangladesh", "bangladesch"], tz: "Asia/Dhaka" },
  { name: "Barbados", aliases: ["barbados"], tz: "America/Barbados" },
  { name: "Belarus", aliases: ["belarus", "bielorrusia", "bielorussie", "weissrussland"], tz: "Europe/Minsk" },
  { name: "Belgium", aliases: ["belgium", "belgique", "belgie", "belgi\u00eb", "belgica", "b\u00e9lgica", "belgien"], tz: "Europe/Brussels" },
  { name: "Belize", aliases: ["belize", "belice"], tz: "America/Belize" },
  { name: "Benin", aliases: ["benin"], tz: "Africa/Porto-Novo" },
  { name: "Bermuda", aliases: ["bermuda"], tz: "Atlantic/Bermuda" },
  { name: "Bhutan", aliases: ["bhutan"], tz: "Asia/Thimphu" },
  { name: "Bolivia", aliases: ["bolivia", "bolivie", "bolivien", "bol\u00edvia"], tz: "America/La_Paz" },
  { name: "Bosnia and Herzegovina", aliases: ["bosnia", "bosnia and herzegovina", "bosnia herzegovina", "bosnien"], tz: "Europe/Sarajevo" },
  { name: "Botswana", aliases: ["botswana", "botsuana"], tz: "Africa/Gaborone" },
  { name: "Brunei", aliases: ["brunei"], tz: "Asia/Brunei" },
  { name: "Bulgaria", aliases: ["bulgaria", "bulgarie", "bulgarien"], tz: "Europe/Sofia" },
  { name: "Burkina Faso", aliases: ["burkina faso", "burkina"], tz: "Africa/Ouagadougou" },
  { name: "Burundi", aliases: ["burundi"], tz: "Africa/Bujumbura" },
  { name: "Cambodia", aliases: ["cambodia", "camboya", "cambodge", "kambodscha"], tz: "Asia/Phnom_Penh" },
  { name: "Cameroon", aliases: ["cameroon", "camerun", "camer\u00fan", "cameroun", "kamerun", "camaroes", "camar\u00f5es"], tz: "Africa/Douala" },
  { name: "Canary Islands (Spain)", aliases: ["canary islands", "canarias", "islas canarias", "the canaries", "canaries"], tz: "Atlantic/Canary" },
  { name: "Cape Verde", aliases: ["cape verde", "cabo verde"], tz: "Atlantic/Cape_Verde" },
  { name: "Cayman Islands", aliases: ["cayman islands", "the caymans", "caymans"], tz: "America/Cayman" },
  { name: "Chad", aliases: ["chad", "tchad"], tz: "Africa/Ndjamena" },
  { name: "China", aliases: ["china", "mainland china", "peoples republic of china", "people's republic of china", "prc", "chine", "zhongguo"], tz: "Asia/Shanghai" },
  { name: "Colombia", aliases: ["colombia", "colombie", "kolumbien", "col\u00f4mbia"], tz: "America/Bogota" },
  { name: "Costa Rica", aliases: ["costa rica"], tz: "America/Costa_Rica" },
  { name: "Croatia", aliases: ["croatia", "croacia", "croatie", "kroatien", "hrvatska"], tz: "Europe/Zagreb" },
  { name: "Cuba", aliases: ["cuba", "kuba"], tz: "America/Havana" },
  { name: "Curacao", aliases: ["curacao", "cura\u00e7ao"], tz: "America/Curacao" },
  { name: "Cyprus", aliases: ["cyprus", "chipre", "chypre", "zypern"], tz: "Asia/Nicosia" },
  { name: "Czech Republic", aliases: ["czech republic", "czechia", "czech", "chequia", "republica checa", "tschechien", "tchequie"], tz: "Europe/Prague" },
  { name: "Denmark", aliases: ["denmark", "dinamarca", "danemark", "danmark", "d\u00e4nemark"], tz: "Europe/Copenhagen" },
  { name: "Djibouti", aliases: ["djibouti"], tz: "Africa/Djibouti" },
  { name: "Dominica", aliases: ["dominica"], tz: "America/Dominica" },
  { name: "Dominican Republic", aliases: ["dominican republic", "the dominican republic", "republica dominicana", "rep\u00fablica dominicana", "santo domingo"], tz: "America/Santo_Domingo" },
  { name: "Ecuador", aliases: ["ecuador", "equateur", "\u00e9quateur", "equador"], tz: "America/Guayaquil" },
  { name: "Egypt", aliases: ["egypt", "egipto", "egypte", "\u00e9gypte", "agypten", "\u00e4gypten", "egito"], tz: "Africa/Cairo" },
  { name: "El Salvador", aliases: ["el salvador", "salvador"], tz: "America/El_Salvador" },
  { name: "Eritrea", aliases: ["eritrea"], tz: "Africa/Asmara" },
  { name: "Estonia", aliases: ["estonia", "estonie", "estland", "eesti"], tz: "Europe/Tallinn" },
  { name: "Eswatini", aliases: ["eswatini", "swaziland"], tz: "Africa/Mbabane" },
  { name: "Ethiopia", aliases: ["ethiopia", "etiopia", "etiop\u00eda", "ethiopie", "athiopien", "\u00e4thiopien"], tz: "Africa/Addis_Ababa" },
  { name: "Fiji", aliases: ["fiji", "fiyi", "fidschi", "fidji"], tz: "Pacific/Fiji" },
  { name: "Finland", aliases: ["finland", "finlandia", "finlande", "finnland", "suomi"], tz: "Europe/Helsinki" },
  { name: "France", aliases: ["france", "francia", "frankreich", "franca", "fran\u00e7a", "france metropolitaine"], tz: "Europe/Paris" },
  { name: "French Guiana", aliases: ["french guiana"], tz: "America/Cayenne" },
  { name: "French Polynesia", aliases: ["french polynesia", "tahiti"], tz: "Pacific/Tahiti" },
  { name: "Gabon", aliases: ["gabon"], tz: "Africa/Libreville" },
  { name: "Gambia", aliases: ["gambia", "the gambia"], tz: "Africa/Banjul" },
  { name: "Georgia (country)", aliases: ["republic of georgia", "georgia country", "georgien", "georgie"], tz: "Asia/Tbilisi" },
  { name: "Germany", aliases: ["germany", "deutschland", "alemania", "allemagne", "alemanha"], tz: "Europe/Berlin" },
  { name: "Ghana", aliases: ["ghana", "gana"], tz: "Africa/Accra" },
  { name: "Gibraltar", aliases: ["gibraltar"], tz: "Europe/Gibraltar" },
  { name: "Greece", aliases: ["greece", "grecia", "grece", "gr\u00e8ce", "griechenland", "hellas"], tz: "Europe/Athens" },
  { name: "Greenland", aliases: ["greenland"], tz: "America/Nuuk" },
  { name: "Grenada", aliases: ["grenada"], tz: "America/Grenada" },
  { name: "Guadeloupe", aliases: ["guadeloupe"], tz: "America/Guadeloupe" },
  { name: "Guatemala", aliases: ["guatemala"], tz: "America/Guatemala" },
  { name: "Guinea", aliases: ["guinea"], tz: "Africa/Conakry" },
  { name: "Guyana", aliases: ["guyana"], tz: "America/Guyana" },
  { name: "Haiti", aliases: ["haiti", "hait\u00ed", "ha\u00efti"], tz: "America/Port-au-Prince" },
  { name: "Honduras", aliases: ["honduras"], tz: "America/Tegucigalpa" },
  { name: "Hong Kong", aliases: ["hong kong", "hongkong", "xianggang"], tz: "Asia/Hong_Kong" },
  { name: "Hungary", aliases: ["hungary", "hungria", "hungr\u00eda", "hongrie", "ungarn", "magyarorszag"], tz: "Europe/Budapest" },
  { name: "Iceland", aliases: ["iceland", "islandia", "islande"], tz: "Atlantic/Reykjavik" },
  { name: "India", aliases: ["india", "inde", "indien", "bharat"], tz: "Asia/Kolkata" },
  { name: "Iran", aliases: ["iran", "ir\u00e1n", "persia"], tz: "Asia/Tehran" },
  { name: "Iraq", aliases: ["iraq", "irak"], tz: "Asia/Baghdad" },
  { name: "Ireland", aliases: ["ireland", "republic of ireland", "eire", "irlanda", "irlande", "irland"], tz: "Europe/Dublin" },
  { name: "Israel", aliases: ["israel", "isra\u00ebl"], tz: "Asia/Jerusalem" },
  { name: "Italy", aliases: ["italy", "italia", "italie", "italien"], tz: "Europe/Rome" },
  { name: "Ivory Coast", aliases: ["ivory coast", "cote d'ivoire", "c\u00f4te d'ivoire", "cote divoire", "costa de marfil", "costa do marfim"], tz: "Africa/Abidjan" },
  { name: "Jamaica", aliases: ["jamaica", "jamaika", "jamaique", "jama\u00efque"], tz: "America/Jamaica" },
  { name: "Japan", aliases: ["japan", "japon", "jap\u00f3n", "japao", "jap\u00e3o", "nihon", "nippon", "riben"], tz: "Asia/Tokyo" },
  { name: "Jordan", aliases: ["jordan", "jordania", "jordanie", "jordanien"], tz: "Asia/Amman" },
  { name: "Kazakhstan", aliases: ["kazakhstan", "kasachstan"], tz: "Asia/Almaty" },
  { name: "Kenya", aliases: ["kenya", "kenia", "quenia", "qu\u00eania"], tz: "Africa/Nairobi" },
  { name: "Kosovo", aliases: ["kosovo"], tz: "Europe/Belgrade" },
  { name: "Kuwait", aliases: ["kuwait", "koweit", "kowe\u00eft"], tz: "Asia/Kuwait" },
  { name: "Kyrgyzstan", aliases: ["kyrgyzstan", "kirguistan", "kirgisistan"], tz: "Asia/Bishkek" },
  { name: "Laos", aliases: ["laos"], tz: "Asia/Vientiane" },
  { name: "Latvia", aliases: ["latvia", "letonia", "lettonie", "lettland", "latvija"], tz: "Europe/Riga" },
  { name: "Lebanon", aliases: ["lebanon", "libano", "l\u00edbano", "liban", "libanon"], tz: "Asia/Beirut" },
  { name: "Lesotho", aliases: ["lesotho"], tz: "Africa/Maseru" },
  { name: "Liberia", aliases: ["liberia"], tz: "Africa/Monrovia" },
  { name: "Libya", aliases: ["libya", "libia", "libye", "libyen"], tz: "Africa/Tripoli" },
  { name: "Liechtenstein", aliases: ["liechtenstein"], tz: "Europe/Vaduz" },
  { name: "Lithuania", aliases: ["lithuania", "lituania", "lituanie", "litauen", "lietuva"], tz: "Europe/Vilnius" },
  { name: "Luxembourg", aliases: ["luxembourg", "luxemburgo", "luxemburg"], tz: "Europe/Luxembourg" },
  { name: "Macau", aliases: ["macau", "macao"], tz: "Asia/Macau" },
  { name: "Madagascar", aliases: ["madagascar", "madagaskar"], tz: "Indian/Antananarivo" },
  { name: "Madeira", aliases: ["madeira"], tz: "Atlantic/Madeira" },
  { name: "Malawi", aliases: ["malawi"], tz: "Africa/Blantyre" },
  { name: "Malaysia", aliases: ["malaysia", "malasia", "malaisie"], tz: "Asia/Kuala_Lumpur" },
  { name: "Maldives", aliases: ["maldives", "maldivas", "the maldives"], tz: "Indian/Maldives" },
  { name: "Mali", aliases: ["mali"], tz: "Africa/Bamako" },
  { name: "Malta", aliases: ["malta", "malte"], tz: "Europe/Malta" },
  { name: "Martinique", aliases: ["martinique"], tz: "America/Martinique" },
  { name: "Mauritania", aliases: ["mauritania"], tz: "Africa/Nouakchott" },
  { name: "Mauritius", aliases: ["mauritius"], tz: "Indian/Mauritius" },
  { name: "Moldova", aliases: ["moldova", "moldavia", "moldavie", "moldawien"], tz: "Europe/Chisinau" },
  { name: "Monaco", aliases: ["monaco"], tz: "Europe/Monaco" },
  { name: "Montenegro", aliases: ["montenegro"], tz: "Europe/Podgorica" },
  { name: "Morocco", aliases: ["morocco", "marruecos", "maroc", "marokko", "marrocos"], tz: "Africa/Casablanca" },
  { name: "Mozambique", aliases: ["mozambique", "mocambique", "mo\u00e7ambique", "mosambik"], tz: "Africa/Maputo" },
  { name: "Myanmar", aliases: ["myanmar", "burma", "birmania", "birmanie"], tz: "Asia/Yangon" },
  { name: "Namibia", aliases: ["namibia", "namibie"], tz: "Africa/Windhoek" },
  { name: "Nepal", aliases: ["nepal"], tz: "Asia/Kathmandu" },
  { name: "Netherlands", aliases: ["netherlands", "the netherlands", "holland", "nederland", "paises bajos", "pa\u00edses bajos", "pays-bas", "niederlande"], tz: "Europe/Amsterdam" },
  { name: "New Caledonia", aliases: ["new caledonia"], tz: "Pacific/Noumea" },
  { name: "New Zealand", aliases: ["new zealand", "nz", "nueva zelanda", "nouvelle-zelande", "nouvelle zelande", "neuseeland", "nova zelandia", "nova zel\u00e2ndia", "aotearoa"], tz: "Pacific/Auckland" },
  { name: "Nicaragua", aliases: ["nicaragua"], tz: "America/Managua" },
  { name: "Niger", aliases: ["niger"], tz: "Africa/Niamey" },
  { name: "Nigeria", aliases: ["nigeria", "nig\u00e9ria"], tz: "Africa/Lagos" },
  { name: "North Korea", aliases: ["north korea"], tz: "Asia/Pyongyang" },
  { name: "North Macedonia", aliases: ["north macedonia", "macedonia"], tz: "Europe/Skopje" },
  { name: "Norway", aliases: ["norway", "noruega", "norvege", "norv\u00e8ge", "norwegen", "norge"], tz: "Europe/Oslo" },
  { name: "Oman", aliases: ["oman", "om\u00e1n"], tz: "Asia/Muscat" },
  { name: "Pakistan", aliases: ["pakistan", "paquistan", "paquist\u00e3o"], tz: "Asia/Karachi" },
  { name: "Palestine", aliases: ["palestine", "palestina"], tz: "Asia/Hebron" },
  { name: "Panama", aliases: ["panama", "panam\u00e1"], tz: "America/Panama" },
  { name: "Papua New Guinea", aliases: ["papua new guinea", "png", "papua nueva guinea"], tz: "Pacific/Port_Moresby" },
  { name: "Paraguay", aliases: ["paraguay", "paraguai"], tz: "America/Asuncion" },
  { name: "Peru", aliases: ["peru", "per\u00fa", "perou", "p\u00e9rou"], tz: "America/Lima" },
  { name: "Philippines", aliases: ["philippines", "the philippines", "filipinas", "pilipinas", "filipinen"], tz: "Asia/Manila" },
  { name: "Poland", aliases: ["poland", "polska", "polonia", "polen", "pologne"], tz: "Europe/Warsaw" },
  { name: "Portugal", aliases: ["portugal", "mainland portugal"], tz: "Europe/Lisbon" },
  { name: "Puerto Rico", aliases: ["puerto rico"], tz: "America/Puerto_Rico" },
  { name: "Qatar", aliases: ["qatar", "katar"], tz: "Asia/Qatar" },
  { name: "Republic of the Congo", aliases: ["republic of the congo", "congo-brazzaville", "congo brazzaville"], tz: "Africa/Brazzaville" },
  { name: "Reunion", aliases: ["reunion", "r\u00e9union"], tz: "Indian/Reunion" },
  { name: "Romania", aliases: ["romania", "rumania", "ruman\u00eda", "roumanie", "rumanien", "rum\u00e4nien"], tz: "Europe/Bucharest" },
  { name: "Rwanda", aliases: ["rwanda", "ruanda"], tz: "Africa/Kigali" },
  { name: "Saint Kitts and Nevis", aliases: ["saint kitts", "st kitts"], tz: "America/St_Kitts" },
  { name: "Saint Lucia", aliases: ["saint lucia", "st lucia"], tz: "America/St_Lucia" },
  { name: "Saint Vincent and the Grenadines", aliases: ["saint vincent", "st vincent"], tz: "America/St_Vincent" },
  { name: "Samoa", aliases: ["samoa"], tz: "Pacific/Apia" },
  { name: "Saudi Arabia", aliases: ["saudi arabia", "saudi", "arabia saudita", "arabie saoudite", "saudi-arabien", "saudi arabien"], tz: "Asia/Riyadh" },
  { name: "Senegal", aliases: ["senegal", "s\u00e9n\u00e9gal"], tz: "Africa/Dakar" },
  { name: "Serbia", aliases: ["serbia", "serbie", "serbien", "srbija"], tz: "Europe/Belgrade" },
  { name: "Seychelles", aliases: ["seychelles"], tz: "Indian/Mahe" },
  { name: "Sierra Leone", aliases: ["sierra leone"], tz: "Africa/Freetown" },
  { name: "Singapore", aliases: ["singapore", "singapur", "singapour", "singapura", "xinjiapo"], tz: "Asia/Singapore" },
  { name: "Slovakia", aliases: ["slovakia", "slovak republic", "eslovaquia", "slowakei", "slovaquie"], tz: "Europe/Bratislava" },
  { name: "Slovenia", aliases: ["slovenia", "eslovenia", "slovenie", "slowenien"], tz: "Europe/Ljubljana" },
  { name: "Somalia", aliases: ["somalia"], tz: "Africa/Mogadishu" },
  { name: "South Africa", aliases: ["south africa", "sudafrica", "sud\u00e1frica", "afrique du sud", "sudafrika", "s\u00fcdafrika", "africa do sul", "\u00e1frica do sul"], tz: "Africa/Johannesburg" },
  { name: "South Korea", aliases: ["south korea", "korea", "republic of korea", "corea", "corea del sur", "coree du sud", "cor\u00e9e du sud", "sudkorea", "s\u00fcdkorea", "hanguo"], tz: "Asia/Seoul" },
  { name: "South Sudan", aliases: ["south sudan", "sudan del sur"], tz: "Africa/Juba" },
  { name: "Spain", aliases: ["spain", "espana", "espa\u00f1a", "espagne", "spanien", "espanha", "spain mainland", "mainland spain"], tz: "Europe/Madrid" },
  { name: "Sri Lanka", aliases: ["sri lanka", "ceylon"], tz: "Asia/Colombo" },
  { name: "Sudan", aliases: ["sudan", "soudan", "sud\u00e1n"], tz: "Africa/Khartoum" },
  { name: "Suriname", aliases: ["suriname", "surinam"], tz: "America/Paramaribo" },
  { name: "Sweden", aliases: ["sweden", "suecia", "suede", "su\u00e8de", "schweden", "sverige"], tz: "Europe/Stockholm" },
  { name: "Switzerland", aliases: ["switzerland", "suisse", "schweiz", "suiza", "suica", "su\u00ed\u00e7a", "svizzera"], tz: "Europe/Zurich" },
  { name: "Syria", aliases: ["syria", "siria"], tz: "Asia/Damascus" },
  { name: "Taiwan", aliases: ["taiwan"], tz: "Asia/Taipei" },
  { name: "Tajikistan", aliases: ["tajikistan", "tayikistan"], tz: "Asia/Dushanbe" },
  { name: "Tanzania", aliases: ["tanzania", "tanzanie", "tansania"], tz: "Africa/Dar_es_Salaam" },
  { name: "Thailand", aliases: ["thailand", "tailandia", "thailande", "tha\u00eflande"], tz: "Asia/Bangkok" },
  { name: "Timor-Leste", aliases: ["timor-leste", "east timor", "timor leste"], tz: "Asia/Dili" },
  { name: "Togo", aliases: ["togo"], tz: "Africa/Lome" },
  { name: "Tonga", aliases: ["tonga"], tz: "Pacific/Tongatapu" },
  { name: "Trinidad and Tobago", aliases: ["trinidad and tobago", "trinidad", "trinidad y tobago"], tz: "America/Port_of_Spain" },
  { name: "Tunisia", aliases: ["tunisia", "tunez", "t\u00fanez", "tunisie", "tunesien"], tz: "Africa/Tunis" },
  { name: "Turkey", aliases: ["turkey", "turkiye", "t\u00fcrkiye", "turquia", "turqu\u00eda", "turquie", "turkei", "t\u00fcrkei"], tz: "Europe/Istanbul" },
  { name: "Turkmenistan", aliases: ["turkmenistan"], tz: "Asia/Ashgabat" },
  { name: "Uganda", aliases: ["uganda", "ouganda"], tz: "Africa/Kampala" },
  { name: "Ukraine", aliases: ["ukraine", "ucrania", "ukraina", "ucr\u00e2nia"], tz: "Europe/Kyiv" },
  { name: "United Arab Emirates", aliases: ["uae", "united arab emirates", "the emirates", "emirates", "emiratos arabes unidos", "emirats arabes unis", "dubai", "abu dhabi"], tz: "Asia/Dubai" },
  { name: "United Kingdom", aliases: ["uk", "united kingdom", "england", "britain", "great britain", "scotland", "wales", "northern ireland", "reino unido", "inglaterra", "angleterre", "royaume-uni", "grossbritannien", "gro\u00dfbritannien"], tz: "Europe/London" },
  { name: "Uruguay", aliases: ["uruguay", "uruguai"], tz: "America/Montevideo" },
  { name: "Uzbekistan", aliases: ["uzbekistan", "usbekistan", "ouzbekistan"], tz: "Asia/Tashkent" },
  { name: "Venezuela", aliases: ["venezuela"], tz: "America/Caracas" },
  { name: "Vietnam", aliases: ["vietnam", "viet nam"], tz: "Asia/Ho_Chi_Minh" },
  { name: "Yemen", aliases: ["yemen"], tz: "Asia/Aden" },
  { name: "Zambia", aliases: ["zambia", "zambie", "sambia"], tz: "Africa/Lusaka" },
  { name: "Zimbabwe", aliases: ["zimbabwe", "simbabwe"], tz: "Africa/Harare" },
];

/** Multi-zone countries — 6 asks for the nearest big city instead. */
export const MULTI_TZ_COUNTRIES: string[] = [
  "america",
  "amerika",
  "australia",
  "australie",
  "australien",
  "brasil",
  "brasilien",
  "brazil",
  "bresil",
  "br\u00e9sil",
  "canada",
  "chile",
  "congo",
  "democratic republic of the congo",
  "dr congo",
  "drc",
  "estados unidos",
  "estados unidos de america",
  "etats-unis",
  "indonesia",
  "indonesie",
  "indonesien",
  "kanada",
  "kasachstan",
  "mejico",
  "mexico",
  "mongolei",
  "mongolia",
  "mongolie",
  "m\u00e9xico",
  "rusia",
  "russia",
  "russie",
  "russland",
  "states",
  "the states",
  "the us",
  "the usa",
  "u s",
  "u s a",
  "united states",
  "us",
  "usa",
  "vereinigte staaten",
  "\u00e9tats-unis",
];
