-- Independent aiASAP database-side watcher for the Vercel cloud heartbeat.
-- No secret values belong in this migration. Optional delivery credentials live
-- in Supabase Vault under the aiASAP-specific names referenced below.

create extension if not exists pg_cron;
create extension if not exists pg_net;

create table if not exists public.aiasap_cloud_watchdog_state (
  singleton boolean primary key default true check (singleton),
  incident_open boolean not null default false,
  incident_started_at timestamptz,
  last_heartbeat_at timestamptz,
  last_checked_at timestamptz,
  last_alert_at timestamptz,
  last_recovery_at timestamptz,
  last_status text not null default 'uninitialised',
  last_detail text,
  updated_at timestamptz not null default now()
);

create table if not exists public.aiasap_cloud_watchdog_checks (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  heartbeat_at timestamptz,
  status text not null check (status in ('healthy', 'stale', 'missing')),
  incident_open boolean not null,
  email_queued boolean not null default false,
  telegram_queued boolean not null default false,
  detail text
);

alter table public.aiasap_cloud_watchdog_state enable row level security;
alter table public.aiasap_cloud_watchdog_checks enable row level security;
revoke all on public.aiasap_cloud_watchdog_state from public, anon, authenticated;
revoke all on public.aiasap_cloud_watchdog_checks from public, anon, authenticated;

create or replace function public.aiasap_cloud_watchdog_tick(p_send boolean default true)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, vault, net
as $$
declare
  v_now timestamptz := now();
  v_heartbeat timestamptz;
  v_status text;
  v_detail text;
  v_state public.aiasap_cloud_watchdog_state%rowtype;
  v_should_notify boolean := false;
  v_is_recovery boolean := false;
  v_email_queued boolean := false;
  v_telegram_queued boolean := false;
  v_resend_key text;
  v_email_from text;
  v_email_to text;
  v_tg_token text;
  v_tg_chat text;
  v_subject text;
  v_message text;
  v_request_id bigint;
begin
  select max(created_at) into v_heartbeat
  from public.app_events
  where event_type = 'cloud_watch_heartbeat'
    and surface = 'aiasap';

  if v_heartbeat is null then
    v_status := 'missing';
    v_detail := 'No aiASAP cloud_watch_heartbeat row exists.';
  elsif v_heartbeat < v_now - interval '35 minutes' then
    v_status := 'stale';
    v_detail := format('Latest heartbeat is %s minutes old.', floor(extract(epoch from (v_now - v_heartbeat)) / 60));
  else
    v_status := 'healthy';
    v_detail := 'Latest aiASAP cloud heartbeat is within 35 minutes.';
  end if;

  insert into public.aiasap_cloud_watchdog_state(singleton)
  values (true)
  on conflict (singleton) do nothing;

  select * into v_state
  from public.aiasap_cloud_watchdog_state
  where singleton = true
  for update;

  if v_status in ('missing', 'stale') then
    if not v_state.incident_open then
      v_state.incident_open := true;
      v_state.incident_started_at := v_now;
    end if;
    v_should_notify := v_state.last_alert_at is null
      or v_state.last_alert_at <= v_now - interval '60 minutes';
  elsif v_state.incident_open then
    v_should_notify := true;
    v_is_recovery := true;
  end if;

  if p_send and v_should_notify then
    select decrypted_secret into v_resend_key from vault.decrypted_secrets where name = 'aiasap_watchdog_resend_api_key' limit 1;
    select decrypted_secret into v_email_from from vault.decrypted_secrets where name = 'aiasap_watchdog_email_from' limit 1;
    select decrypted_secret into v_email_to from vault.decrypted_secrets where name = 'aiasap_watchdog_email_to' limit 1;
    select decrypted_secret into v_tg_token from vault.decrypted_secrets where name = 'aiasap_watchdog_telegram_bot_token' limit 1;
    select decrypted_secret into v_tg_chat from vault.decrypted_secrets where name = 'aiasap_watchdog_telegram_chat_id' limit 1;

    v_subject := case when v_is_recovery then 'aiASAP cloud heartbeat recovered' else 'aiASAP cloud heartbeat alert' end;
    v_message := case when v_is_recovery
      then 'aiASAP cloud heartbeat is healthy again.'
      else 'aiASAP independent watcher detected a stale or missing Vercel heartbeat. ' || v_detail
    end;

    -- Queue email first, only when the complete independent email channel exists.
    if coalesce(v_resend_key, '') <> '' and coalesce(v_email_from, '') <> '' and coalesce(v_email_to, '') <> '' then
      select net.http_post(
        url := 'https://api.resend.com/emails',
        headers := jsonb_build_object('Authorization', 'Bearer ' || v_resend_key, 'Content-Type', 'application/json'),
        body := jsonb_build_object('from', v_email_from, 'to', jsonb_build_array(v_email_to), 'subject', v_subject, 'text', v_message)
      ) into v_request_id;
      v_email_queued := v_request_id is not null;
    end if;

    -- Queue Telegram second, only when both bot token and destination exist.
    if coalesce(v_tg_token, '') <> '' and coalesce(v_tg_chat, '') <> '' then
      select net.http_post(
        url := 'https://api.telegram.org/bot' || v_tg_token || '/sendMessage',
        headers := jsonb_build_object('Content-Type', 'application/json'),
        body := jsonb_build_object('chat_id', v_tg_chat, 'text', v_message, 'disable_web_page_preview', true)
      ) into v_request_id;
      v_telegram_queued := v_request_id is not null;
    end if;

    if v_email_queued or v_telegram_queued then
      if v_is_recovery then
        v_state.last_recovery_at := v_now;
      else
        v_state.last_alert_at := v_now;
      end if;
    else
      v_detail := v_detail || ' Delivery skipped: required Vault channel secrets are incomplete.';
    end if;
  end if;

  if v_status = 'healthy' then
    v_state.incident_open := false;
    v_state.incident_started_at := null;
  end if;

  update public.aiasap_cloud_watchdog_state set
    incident_open = v_state.incident_open,
    incident_started_at = v_state.incident_started_at,
    last_heartbeat_at = v_heartbeat,
    last_checked_at = v_now,
    last_alert_at = v_state.last_alert_at,
    last_recovery_at = v_state.last_recovery_at,
    last_status = v_status,
    last_detail = v_detail,
    updated_at = v_now
  where singleton = true;

  insert into public.aiasap_cloud_watchdog_checks(heartbeat_at, status, incident_open, email_queued, telegram_queued, detail)
  values (v_heartbeat, v_status, v_state.incident_open, v_email_queued, v_telegram_queued, v_detail);

  delete from public.aiasap_cloud_watchdog_checks where checked_at < v_now - interval '30 days';

  return jsonb_build_object(
    'status', v_status,
    'heartbeat_at', v_heartbeat,
    'incident_open', v_state.incident_open,
    'email_queued', v_email_queued,
    'telegram_queued', v_telegram_queued,
    'delivery_configured', (v_email_queued or v_telegram_queued),
    'detail', v_detail
  );
exception when others then
  -- Fail closed: no retry loop and no fallback destination.
  update public.aiasap_cloud_watchdog_state set
    last_checked_at = v_now,
    last_status = 'error',
    last_detail = left(sqlstate || ': ' || sqlerrm, 500),
    updated_at = v_now
  where singleton = true;
  return jsonb_build_object('status', 'error', 'delivery_configured', false);
end;
$$;

revoke all on function public.aiasap_cloud_watchdog_tick(boolean) from public, anon, authenticated;
grant execute on function public.aiasap_cloud_watchdog_tick(boolean) to postgres, service_role;

do $$
declare v_job_id bigint;
begin
  for v_job_id in select jobid from cron.job where jobname = 'aiasap-cloud-heartbeat-watchdog'
  loop
    perform cron.unschedule(v_job_id);
  end loop;
  perform cron.schedule(
    'aiasap-cloud-heartbeat-watchdog',
    '*/5 * * * *',
    $job$select public.aiasap_cloud_watchdog_tick(true);$job$
  );
end;
$$;

comment on function public.aiasap_cloud_watchdog_tick(boolean) is
  'Independent Supabase-side aiASAP heartbeat watcher. p_send=false is deterministic no-contact verification.';
